services:
  nginx:
    container_name: nginx-alpine
    image: "nginx:stable-alpine"
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    command: /bin/sh -c "chmod -R 777 /var/www/laravel/storage && nginx -g 'daemon off;'"
    depends_on:
      - php
      - mysql
  php:
    container_name: php83
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    container_name: mysql
    image: mysql:9.2
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql

  composer:
    user: "1000:1000"
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    container_name: artisan
    user: "1000:1000"
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

#Volumes
volumes:
  dbdata: